name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name"
        required: true
        default: "My App"

      package_name:
        description: "Package Name"
        required: true
        default: "com.myapp.test"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Update App Name
        run: |
          echo '<resources>
          <string name="app_name">${{ github.event.inputs.app_name }}</string>
          </resources>' > android-template/WebAppEngine/app/src/main/res/values/strings.xml

      - name: Update Package Name
        run: |
          sed -i 's/namespace = ".*"/namespace = "${{ github.event.inputs.package_name }}"/' android-template/WebAppEngine/app/build.gradle.kts

          sed -i 's/applicationId = ".*"/applicationId = "${{ github.event.inputs.package_name }}"/' android-template/WebAppEngine/app/build.gradle.kts

      - name: Grant Gradle Permission
        run: chmod +x gradlew
        working-directory: android-template/WebAppEngine

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: android-template/WebAppEngine

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: generated-apk
          path: android-template/WebAppEngine/app/build/outputs/apk/debug/app-debug.apk